apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistentvolumeclaim
  namespace: monitoring
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      securityContext: # Gives Grafana permission to write the pv without being root (472 is the group of the grafana user)
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-persistentvolume
      volumes:
        - name: grafana-persistentvolume
          persistentVolumeClaim:
            claimName: grafana-persistentvolumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  ports: 
    - port: 3000
      targetPort: http-grafana
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-grafana-network-policy"
  namespace: monitoring # Apply the network policy on namespace monitoring
spec:
  podSelector:
    matchLabels:
      app: grafana # Apply the network policy to pods having label app=grafana (and, because of namespace metadata, in namespace monitoring)
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3000 # Allow access to port 3000 (Grafana) from every source (necessary to see Grafana UI)
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 9090   # Grafana -> Prometheus
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app: loki
      ports:
        - port: 3100   # Grafana -> Loki
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-prometheus-network-policy"
  namespace: monitoring # Apply the network policy on namespace monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus # Apply the network policy to pods having label app=prometheus (and, because of namespace metadata, in namespace monitoring)
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: # Allow access to Prometheus from the monitoring namespace, specifically from Grafana
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: grafana
      ports:
        - port: 9090 # Allow access to port 9090 (Prometheus)
    - from: # Allow access to Prometheus from the monitoring namespace, specifically from prometheus-adapter
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: prometheus-adapter
      ports:
        - port: 9090 # Allow access to port 9090 (Prometheus)
  egress:
    - to: # Allow communication to pods in frontend namespace with label type=frontend for monitoring, port 9090
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: frontend
        podSelector:
            matchLabels:
              type: frontend
      ports:
        - port: 9090
    - to: # Allow communication to pods in backend namespace with label type=backend for monitoring, port 9104
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: backend
        podSelector:
            matchLabels:
              type: backend
      ports:
        - port: 9104
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-loki-network-policy"
  namespace: monitoring # Apply the network policy on namespace monitoring
spec:
  podSelector:
    matchLabels:
      app: loki # Apply the network policy to pods having label app=loki (and, because of namespace metadata, in namespace monitoring)
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: # Allow access to loki from the monitoring namespace, specifically from Grafana
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app.kubernetes.io/name: fluent-bit
      ports:
        - port: 3100
    - from: # Allow access to loki from the monitoring namespace, specifically from Grafana
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: grafana
      ports:
        - port: 3100
    - from: # Allow access to loki from the monitoring namespace, specifically from loki-canary
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: loki-canary
      ports:
        - port: 3100
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-loki-canary-network-policy"
  namespace: monitoring # Apply the network policy on namespace monitoring
spec:
  podSelector:
    matchLabels:
      app: loki-canary # Apply the network policy to pods having label app=loki-canary (and, because of namespace metadata, in namespace monitoring)
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to: # Allow loki-canary to send data to loki (loki-canary is a daemonset)
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: loki
      ports:
        - port: 3100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-prometheus-adapter-network-policy"
  namespace: monitoring # Apply the network policy on namespace monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus-adapter # Apply the network policy to pods having label app=prometheus-adapter (and, because of namespace metadata, in namespace monitoring)
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
      - port: 6443 # Allow access to port 6443 (Prometheus adapter) from every source (necessary to make HPA work)
      - port: 443 # Allow access to port 443 (Prometheus adapter /healtz endpoint) (necessary to make HPA work)
  egress:
    - to: # Allow access to Prometheus, port 9090
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 9090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-allow-dns-network-policy"
  namespace: monitoring # Apply the network policy to namespace monitoring
spec:
  podSelector: {} # Apply to all pods in namespace monitoring
  policyTypes:
    - Egress
  egress:
    - to: # Allow DNS
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "monitoring-fluent-bit-network-policy"
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
          matchLabels:
            app: loki
      ports:
        - port: 3100
---
apiVersion: crd.projectcalico.org/v1 # Specific network policy for calico: allow every pod in monitoring to access the kubernetes service in default namespace. Useful to allow access to kubernetes.default.svc (kubernetes API), which is necessary for prometheus and other elements 
kind: NetworkPolicy
metadata:
  name: monitoring-specific-network-policy
  namespace: monitoring
spec:
  selector: all()
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        services:
          name: kubernetes
          namespace: default
  