# TODO: add metrics for MariaDB

prometheus:
  url: http://prometheus-operated.monitoring.svc
  port: 9090

podLabels:
  app: prometheus-adapter

rules:
  default: false
  custom:
    - seriesQuery: 'total_request_qt_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^total_request_qt_total$"
        as: "http_requests_per_second"
      metricsQuery: |
        rate(total_request_qt_total{<<.LabelMatchers>>}[1m])
    - seriesQuery: 'mysql_global_status_commands_total{command="update",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^mysql_global_status_commands_total$"
        as: "mysql_reads_per_second"
      metricsQuery: |
        rate(mysql_global_status_commands_total{command="update",<<.LabelMatchers>>}[1m])
