FROM golang AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM scratch

COPY --from=build /app/app /app

EXPOSE 8080
EXPOSE 9090

ENTRYPOINT ["/app"]
